# -*- coding: utf-8 -*-
from . import hr_contract
from . import hr_payroll_structure
from . import hr_contribution_register
from . import hr_salary_rule_category
from . import hr_salary_rule
from . import hr_payslip
from . import hr_payslip_line
from . import hr_payslip_input
from . import hr_payslip_worked_days
from . import hr_payslip_fine
from . import hr_payslip_run
from . import hr_employee
from . import hr_employee_kpi
from . import hr_payslip_tax_bracket
from . import hr_payslip_register_wizard
from . import account_move
from . import res_company
from . import res_config_settings
