# -*- coding: utf-8 -*-
from odoo import _, api, fields, models
from odoo.exceptions import UserError


class HrPayslipRegisterWizard(models.TransientModel):
    """Generate the aggregate payroll register (PDF or Excel) for a period.

    Collects the confirmed payslips of a company in a date range (optionally
    filtered by salary structure) and prints/export the register.
    """
    _name = 'hr.payslip.register.wizard'
    _description = "Payslip Register Wizard"

    company_id = fields.Many2one(
        'res.company', string="Company", required=True,
        default=lambda self: self.env.company)
    date_from = fields.Date(string="From", required=True)
    date_to = fields.Date(string="To", required=True)
    struct_id = fields.Many2one(
        'hr.payroll.structure', string="Salary Structure",
        help="Optional filter: only payslips of this structure.")
    state = fields.Selection([
        ('done', 'Confirmed'),
        ('verify', 'Waiting'),
        ('draft', 'Draft'),
        ('cancel', 'Cancelled'),
    ], string="Status", default='done')

    @api.model
    def default_get(self, fields_list):
        res = super().default_get(fields_list)
        # default to the current month when no context is provided
        if not res.get('date_from') and not self.env.context.get('default_date_from'):
            today = fields.Date.today()
            res['date_from'] = today.replace(day=1)
            res['date_to'] = today
        return res

    def _get_payslips(self):
        domain = [
            ('company_id', '=', self.company_id.id),
            ('state', '=', self.state),
            ('date_from', '>=', self.date_from),
            ('date_to', '<=', self.date_to),
        ]
        if self.struct_id:
            domain.append(('struct_id', '=', self.struct_id.id))
        payslips = self.env['hr.payslip'].search(
            domain, order='employee_id, date_from')
        return payslips

    def action_print_register(self):
        """Print the register (PDF) of the collected payslips."""
        payslips = self._get_payslips()
        if not payslips:
            raise UserError(_("No confirmed payslips found for the selected "
                              "period and filters."))
        return self.env.ref('ff_hr_payroll.action_report_hr_payslip_register') \
            .report_action(payslips)

    def action_download_xlsx(self):
        """Open the Excel register generated by the export controller."""
        payslips = self._get_payslips()
        if not payslips:
            raise UserError(_("No confirmed payslips found for the selected "
                              "period and filters."))
        ids = ','.join(str(i) for i in payslips.ids)
        return {
            'type': 'ir.actions.act_url',
            'url': '/ff_hr_payroll/payslip_register_xlsx?ids=%s' % ids,
            'target': 'self',
        }
